import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, BarChart3, Bot, BrainCircuit, Check, ChevronDown, Circle, Github } from 'lucide-react';
import { GENAI_PROJECTS, PROJECTS, UI_TEXT } from '../constants';
import { useLanguage } from './LanguageContext';

type Localized = { en: string; pt: string };
type SystemKey = 'data' | 'automation' | 'ai';
type ProjectItem = { title: Localized; subtitle: Localized; description: Localized; tags: string[]; url?: string; repositoryUrl?: string; badge?: Localized };

const automationProjects: ProjectItem[] = [
  { title: { en: 'ContractOps AI', pt: 'ContractOps AI' }, subtitle: { en: 'Intelligent contract registration', pt: 'Cadastramento inteligente de contratos' }, description: { en: 'Corporate RPA that validates contract data and business rules through an API, registers approved records in a legacy ERP and tracks operations in a control tower.', pt: 'RPA corporativo que valida dados contratuais e regras de negócio via API, cadastra contratos aprovados em ERP legado e acompanha a operação em uma torre de controle.' }, tags: ['UiPath', 'FastAPI', 'Python', 'RPA'], url: 'https://contractops-ai-seven.vercel.app/', repositoryUrl: 'https://github.com/geovatatsuga/contractops-ai', badge: { en: 'Featured · Live demo', pt: 'Destaque · Demo ao vivo' } },
  { title: { en: 'Invoice & Purchase Order Reconciliation', pt: 'Automação de Conciliação de Faturas e Pedidos' }, subtitle: { en: 'Accounts payable RPA', pt: 'RPA para contas a pagar' }, description: { en: 'Automation that reads invoice PDFs, reconciles purchase orders, vendors, values and duplicates, then records approval or exception evidence.', pt: 'Automação que lê faturas em PDF, concilia pedidos, fornecedores, valores e duplicidades, registrando evidências de aprovação ou exceção.' }, tags: ['UiPath', 'Python', 'React', 'RPA'], url: 'https://dashboard-beta-snowy-87.vercel.app/', repositoryUrl: 'https://github.com/geovatatsuga/automacao-conciliacao-faturas-pedidos', badge: { en: 'Live demo', pt: 'Demo ao vivo' } },
  { title: { en: 'Contract Routine Automation', pt: 'Automação de Rotinas Contratuais' }, subtitle: { en: 'Contract deadline monitoring and alerts', pt: 'Monitoramento de prazos e alertas contratuais' }, description: { en: 'Google Workspace automation that monitors contract deadlines, sends preventive Gmail alerts and keeps an auditable history in Google Sheets.', pt: 'Automação com Google Workspace que monitora prazos contratuais, envia alertas preventivos pelo Gmail e mantém histórico auditável no Google Sheets.' }, tags: ['Google Apps Script', 'Google Sheets', 'Gmail', 'Automation'], url: 'https://github.com/geovatatsuga/automacao-rotinas-contratuais-appsscript', repositoryUrl: 'https://github.com/geovatatsuga/automacao-rotinas-contratuais-appsscript', badge: { en: 'Professional case', pt: 'Caso profissional' } }
];

const sales = PROJECTS.find(project => project.title.en === 'Sales Intelligence');
const dataProjects = [sales, ...PROJECTS.filter(project => project !== sales && project.title.en !== 'Cereus CRM')].filter(Boolean) as ProjectItem[];
const aiProjects = GENAI_PROJECTS.filter(project => project.title.en !== 'Big Bang Theory') as ProjectItem[];
const systems: Record<SystemKey, { code: string; title: Localized; kicker: Localized; description: Localized; status: Localized; projects: ProjectItem[] }> = {
  data: { code: 'SYS.DATA', title: { en: 'Data Intelligence', pt: 'Inteligência de Dados' }, kicker: { en: 'Analytics • BI • Data Engineering', pt: 'Análise de Dados • BI • Engenharia de Dados' }, description: { en: 'Turning raw data into decisions and analytical systems.', pt: 'Transformando dados brutos em decisões e sistemas analíticos.' }, status: { en: 'Online', pt: 'Online' }, projects: dataProjects },
  automation: { code: 'SYS.AUTO', title: { en: 'Automation Systems', pt: 'Sistemas de Automação' }, kicker: { en: 'RPA • Integration • Process Automation', pt: 'RPA • Integrações • Automação de Processos' }, description: { en: 'Turning repetitive processes into resilient automated workflows.', pt: 'Transformando processos repetitivos em fluxos automatizados e resilientes.' }, status: { en: 'Active', pt: 'Ativo' }, projects: automationProjects },
  ai: { code: 'SYS.AI', title: { en: 'Intelligent Systems', pt: 'Sistemas Inteligentes' }, kicker: { en: 'LLMs • RAG • Agents • Generative AI', pt: 'LLMs • RAG • Agentes • IA Generativa' }, description: { en: 'Building systems that use AI as part of the process.', pt: 'Construindo sistemas que utilizam IA como parte do processo.' }, status: { en: 'Ready', pt: 'Pronto' }, projects: aiProjects }
};

const ptTags: Record<string, string> = { 'Business Intelligence': 'Inteligência de Negócios', 'Data Science': 'Ciência de Dados', 'Dashboard': 'Painel', 'Fraud Detection': 'Detecção de Fraudes', 'Sales Analytics': 'Análise de Vendas', 'Data Visualization': 'Visualização de Dados', 'Data Engineering': 'Engenharia de Dados', 'Generative AI': 'IA Generativa', 'Multi-Agent Systems': 'Sistemas Multiagentes', 'Process Automation': 'Automação de Processos', 'Python Automation': 'Automação com Python', 'Email Workflow': 'Fluxo de E-mails', '~3h/week': '~3h por semana' };

const SystemVisual = ({ type }: { type: SystemKey }) => {
  if (type === 'data') return <div className="flex h-20 items-end gap-2" aria-hidden="true">{[32,55,42,78,62,92,70].map((h,i) => <motion.span key={i} className="w-full border-t border-purple-900/50 bg-purple-900/5" animate={{ height: [`${h}%`,`${Math.max(20,h-22)}%`,`${h}%`] }} transition={{ duration: 2.8, delay: i*.12, repeat: Infinity }} />)}</div>;
  if (type === 'automation') return <div className="flex h-20 items-center text-stone-500" aria-hidden="true">{[Circle,Check,Check,Bot,Check].map((Icon,i) => <React.Fragment key={i}><motion.span animate={{ scale: [1,1.18,1] }} transition={{ duration: 1.8, delay: i*.25, repeat: Infinity }}><Icon className="w-5 h-5" /></motion.span>{i<4 && <motion.span className="h-px flex-1 bg-stone-300" animate={{ opacity:[.25,1,.25] }} transition={{ duration:1.8,delay:i*.25,repeat:Infinity }}/>}</React.Fragment>)}</div>;
  return <div className="relative h-20" aria-hidden="true">{[[12,44],[32,18],[52,56],[72,25],[88,62]].map(([l,t],i)=><motion.span key={i} className="absolute h-2 w-2 rounded-full bg-purple-900/50" style={{left:`${l}%`,top:`${t}%`}} animate={{opacity:[.25,1,.25],scale:[.8,1.4,.8]}} transition={{duration:2.5,delay:i*.35,repeat:Infinity}}/>)}<svg className="absolute inset-0 h-full w-full stroke-stone-300"><path d="M12 38 L32 16 L52 45 L72 20 L88 50" fill="none" strokeWidth="1" strokeDasharray="3 4"/></svg></div>;
};

const Projects: React.FC = () => {
  const { t, language } = useLanguage();
  const [open, setOpen] = useState<SystemKey | null>(null);
  const keys: SystemKey[] = ['data','automation','ai'];
  const icons = { data: BarChart3, automation: Bot, ai: BrainCircuit };
  const tag = (value:string) => language === 'pt' ? ptTags[value] || value : value;

  return <section id="projects" className="scroll-mt-28 md:scroll-mt-32 py-28 px-6 md:px-12 lg:px-24 relative overflow-hidden bg-stone-50/70 border-y border-stone-200">
    <div className="absolute inset-0 opacity-[0.04] pointer-events-none" style={{backgroundImage:'radial-gradient(#1c1917 1px, transparent 1px)',backgroundSize:'22px 22px'}}/>
    <div className="max-w-7xl mx-auto relative z-10">
      <header className="mb-14 flex items-end justify-between border-b border-stone-300 pb-5"><div><span className="font-mono text-xs text-purple-900/60">{t(UI_TEXT.projects.section)}</span><h3 className="font-serif text-4xl md:text-5xl text-obsidian mt-2">{t(UI_TEXT.projects.title)}</h3></div><span className="hidden md:block font-mono text-[10px] text-stone-400">{language==='pt'?'03 PILARES / ARQUITETURA HÍBRIDA':'03 PILLARS / HYBRID ARCHITECTURE'}</span></header>
      <div className="flex flex-col lg:flex-row gap-4 items-stretch">
        {keys.map((key,index) => { const system=systems[key]; const Icon=icons[key]; const expanded=open===key; const surface=key==='data'?'from-sky-50/70 via-white to-white':key==='automation'?'from-orange-50/80 via-white to-amber-50/40':'from-violet-50/70 via-white to-fuchsia-50/30'; const activeBorder=key==='automation'?'border-orange-400/50':key==='data'?'border-sky-400/50':'border-violet-400/50'; return <motion.article key={key} layout="position" className={`min-w-0 lg:basis-0 lg:flex-1 border bg-gradient-to-br ${surface} overflow-hidden transition-all duration-300 hover:-translate-y-1 hover:shadow-lg ${expanded?`${activeBorder} shadow-md`:'border-stone-200'}`}>
          <button type="button" onClick={()=>setOpen(expanded?null:key)} aria-expanded={expanded} className="w-full min-h-[390px] p-6 md:p-7 xl:p-8 text-left flex flex-col group">
            <div className="flex items-center justify-between font-mono text-[10px] tracking-widest"><span className="text-purple-900/60">{system.code}</span><span className="flex items-center gap-2 text-green-600"><i className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse"/>{t(system.status)}</span></div>
            <div className="mt-10 flex items-center gap-3 text-stone-400"><Icon className="w-5 h-5" strokeWidth={1.4}/><span className="font-mono text-[10px]">0{index+1}</span></div>
            <h4 className="font-sans text-2xl xl:text-3xl uppercase leading-[1.12] text-obsidian mt-4 max-w-sm break-words">{t(system.title)}</h4><p className="font-mono text-[9px] xl:text-[10px] uppercase leading-relaxed text-stone-400 mt-3 min-h-[30px]">{t(system.kicker)}</p><p className="font-serif text-base xl:text-lg text-stone-600 leading-relaxed mt-4 max-w-md">{t(system.description)}</p>
            <div className="mt-auto pt-7"><SystemVisual type={key}/><div className="mt-7 pt-4 border-t border-stone-100 flex justify-between items-center font-mono text-[10px] uppercase tracking-widest"><span>{system.projects.length.toString().padStart(2,'0')} {language==='pt'?'projetos':'projects'}</span><span className="flex items-center gap-2 text-purple-900">{expanded?(language==='pt'?'Fechar':'Close'):(language==='pt'?'Explorar':'Explore')}<ChevronDown className={`w-4 h-4 transition-transform duration-300 ${expanded?'rotate-180':''}`}/></span></div></div>
          </button>
          <AnimatePresence initial={false}>{expanded && <motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:1}} transition={{duration:.42,ease:[.22,1,.36,1]}} className="overflow-hidden"><div className="border-t border-stone-200 bg-stone-50 p-5 md:p-7 space-y-3">{system.projects.map((project,i)=><div key={t(project.title)} role={project.url?'link':undefined} tabIndex={project.url?0:undefined} onClick={()=>project.url&&window.open(project.url,'_blank','noopener,noreferrer')} onKeyDown={event=>{if(project.url&&(event.key==='Enter'||event.key===' ')){event.preventDefault();window.open(project.url,'_blank','noopener,noreferrer')}}} className={`group/project grid gap-4 p-5 border border-stone-200 bg-white transition-all duration-300 ${project.url?'cursor-pointer hover:border-purple-900/30 hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-purple-900/30':'cursor-default'}`}><div><span className="font-mono text-[9px] uppercase text-purple-900/60">{project.badge?t(project.badge):i===0?(language==='pt'?'Destaque':'Featured'):`${language==='pt'?'Projeto':'Project'} 0${i+1}`}</span><h5 className="font-serif text-xl text-stone-900 mt-2">{t(project.title)}</h5><p className="font-mono text-[9px] uppercase leading-relaxed text-stone-400 mt-2">{t(project.subtitle)}</p></div><p className="text-sm text-stone-600 leading-relaxed max-w-prose">{t(project.description)}</p><div className="flex flex-wrap items-center justify-between gap-3 border-t border-stone-100 pt-3"><div className="flex flex-wrap gap-1.5">{project.tags.slice(0,4).map(x=><span key={x} className="font-mono text-[8px] bg-stone-100 px-2 py-1 text-stone-500">{tag(x)}</span>)}</div><div className="flex items-center gap-3">{project.repositoryUrl&&<a href={project.repositoryUrl} target="_blank" rel="noreferrer" onClick={event=>event.stopPropagation()} aria-label={`GitHub: ${t(project.title)}`} className="inline-flex items-center gap-1.5 border border-stone-200 px-2.5 py-1.5 font-mono text-[9px] uppercase text-stone-500 hover:border-purple-900/30 hover:text-purple-900"><Github className="w-3.5 h-3.5"/>GitHub</a>}{project.url&&<ArrowUpRight className="w-4 h-4 text-stone-400 group-hover/project:text-purple-900"/>}</div></div></div>)}</div></motion.div>}</AnimatePresence>
        </motion.article>})}
      </div>
      <div className="mt-5 text-right"><a href={GENAI_PROJECTS.find(project=>project.title.en==='Big Bang Theory')?.url} target="_blank" rel="noreferrer" className="font-mono text-[10px] uppercase tracking-widest text-stone-400 hover:text-purple-900">{language==='pt'?'Experimentos / Código criativo':'Experiments / Creative coding'} <ArrowUpRight className="inline w-3 h-3"/></a></div>
    </div>
  </section>;
};

export default Projects;
